### PR TITLE
feat(config): override online status

### PR DESCRIPTION
**Pull request by rokam**
Add an option to keep the last online state on connectivity issue

### CODE REVIEW

**Comment by rokam** [comment]
Fix #30

**Review by mac-zhou — CHANGES_REQUESTED** [review]
There is no `unavailable` status here. The `unavailable` status is in the home assistant.
So please change name to `forced_online`, it is easy to understand.

**Comment by rokam** [comment]
@mac-zhou any additional request?

**Comment by rokam** [comment]
@mac-zhou , can you please bump the version?

**Pull request merged**
